?>
<p><i>Ziel bei Syndicates ist es, die Expansion des eigenen Konzerns möglichst effektiv voran zu treiben, um am Ende eine große Konzernstärke (Networth) zu erreichen.<br><br>
Hier sollen nun verschiedene Konzepte miteinander vergleichen werden, die auf dem Weg des Wachstums nötig sind bzw. bedacht werden sollten.</i></p>
<br>
<p><i>Das wichtigste bei Syndicates sind - wie bei einer Wirtschaftssimulation zu erwarten - die Einnahmen. Diese können auf folgender Basis erzielt werden:</i></p>
<i>1) Produktion<br>
2) Handel<br>
3) Diebstahl<br>
4) Kapital</i><br><br>
<i>1) Produktion</i><br>
Produktion ist der "Standardweg" Einnahmen zu erzielen. Man nimmt schlicht einen Teil seines Landes, bebaut ihn mit Gebäuden, die Ressourcen produzieren und nutzt diese, um sein Wachstum voran zu treiben. Außerdem kann man durch die "Produktion" seiner Ranger / Sentinels (UIC) eine weitere Steigerung der Einnahmen erzielen und gleichzeitig eine brauchbare Verteidigung aufbauen. Sinnvollerweise spezialisiert man sich hier auf ein bis zwei Ressourcen, um den Synergiebonus optimal nutzen zu können und nutzt den Global Market oder das Syndicatslager, um alle weiteren zu erwerben.<br>
Vorteile hierbei sind, dass das ganze ein relativ einfacher Weg zu wachsen ist (geringer Zeitaufwand, nicht schwierig zu spielen). Außerdem hält sich der Forschungsaufwand hierfür deutlich in Grenzen.<br>
Nachteile sind die unter Umständen Anfälligkeit gegenüber Dieben (wenn man sich länger nicht einloggt und keine Syndikatsgebäude, die direkt ins Lager produzieren, verwenden kann oder will) und die Abhängigkeit vom Global Market, eine natürliche Folge der (notwendigen) Spezialisierung. Zusätzlich muss jemand, der effektiv produzieren will, als seine Stufe 5 Forschung Economic Domination wählen.<br><br>
<i>2) Handel</i><br>
Dieser gliedert sich in die Unterpunkte "Ressourcenhandel" und "Einheitenhandel".<br>
Ressourcenhandel ist quasi reine Spekulation. Man versucht billig Ressourcen am Global Market einzukaufen und diese dann teuer wieder zu verkaufen (z.B. Tags über Schnäppchen einsacken und diese am Abend teuer einstellen, so dass sie, wenn morgens alle Creditproduzenten aufstehen und sich einloggen, teuer verkauft werden). Weiterführend kann das sogar so betrieben werden, dass man Credits ansammelt, sich dann bei einem relativ festgesetzten Preis mit einer Ressource einzudecken, um anschließend den Markt so leer zu kaufen, dass man nun selbst der billigste Anbieter ist - gerade dieses funktioniert natürlich optimal im Team.<br>
Einheitenhandel funktioniert auf die Weise, dass man mittels Fabriken / Geheimdienstzentren / Forschungen Einheiten billiger produziert als andere und diese am Globalen Markt verkauft, wobei man dadurch Gewinn macht, dass man mehr verlangt als man selbst für den Bau ausgibt, jedoch weniger als "der Durchschnitt" aufwenden müsste. Eventuell kann man sogar durch Advanced / Hightech Unit Construction Einheiten anbieten, die die Mehrheit gar nicht selbst bauen sondern nur kaufen kann.<br>
Vorteile bei beiden Varianten ist, dass man etwas unabhängiger davon wird, ob nun gerade niedrige oder hohe Ressourcenpreise am Global Market herrschen. Außerdem ist das Wachstumspotential tendenziell recht hoch - vor allem beim Ressourcenhandeln, da dieser quasi kein "Land" braucht. Forschungen werden für Ressourcenhandel keine benötigt und auch Einheitenhandel benötigt keine "wertvolle" Stufe 5 Forschung.<br>
Nachteil hier ist die extreme Anfälligkeit gegenüber Dieben (sofern man nicht selbst eine sehr gute Spydefense besitzt), da man oft viele Ressourcen auf dem Konto hat und durch stärkere Networthschwankungen die Handelsaktivität auch nach außen hin "sichtbar" ist. Außerdem ist das eine relativ zeitfressende Variante, Einnahmen zu erzielen - wer zwei Tage nicht online ist macht auch zwei Tage keinen Gewinn. Für effektive Einheitenproduktion benötigt man außerdem etwas zeitfressende und vor allem sehr teure Forschungen und schließt sich zum Teil andere Forschungen aus (z. B. Hightech Unit Construction gegenüber Better Space Management).<br><br>
<i>3) Diebstahl</i><br>
Hierbei legt man quasi eine Schmarotzermentalität an den Tag. Man baut selbst viele Thiefs / V-Männer und sucht andere Konzerne, die aus verschiedenen Gründen (Zinsen, angelaufene Produktion, Handel am Global Market) viele Ressourcen auf dem Konto haben und klaut diese.<br>
Vorteil hierbei ist, dass man mit ca. 2 bis 3 Logins pro Tag recht hohe Wachstumsraten erzielen kann und außerdem ein gutes Land / Networthverhältnis hat, so da man meist von anderen in Ruhe gelassen wird. Man hat außerdem immer eine relativ gute Spydef, wodurch man recht gut vor Sabotage oder fremden Diebstahl (besonders als SL) geschützt ist.<br> 
Nachteile sind hierbei, dass es ziemlich schwierig sein kann, gute Opfer zu finden. Außerdem macht man sich relativ viele Feinde - und wenn man länger nicht online ist hat man auch hier keine Einnahmen. Außerdem kann man unter vielen Fehlschlägen leiden (tote Spione und damit auch keine Einnahmen aus einer Spionageaktion) und man benötigt viele Forschungen und eigentlich zwingend die Stufe 5 Forschung "Faster Spy Regeneration".<br><br>
<i>4) Kapital</i><br>
Hierbei geht es darum, dass man sein Geld nicht direkt in neues Land / Einheiten / usw. investiert, sondern es spart, um Zinsen zu kriegen (Stufe 2 Forschung, Global Sciences, "Investment Strategies") oder in Aktien steckt, die hoffentlich Dividenden abwerfen und im Wert steigen.<br>
Vorteile hierbei sind, dass man meist sehr direkt eine Steigerung der Einnahmen erzielt (z.B. braucht man keine 20 Stunden, bis gekauftes Land "da" ist, welches auch noch bebaut werden muss) und man außerdem ein gewisses Polster für Notsituationen besitzt. Außerdem benötigt man hierfür kein Land und höchsten (bei Zinsen) minimale Forschungen. Aktien sind außerdem 100% vor Diebstahl, Angriff usw. sicher und man erhält man durch Aktien Schutz vor fremden Syndikaten sowie taktische Mehrinformation durch Einblick in deren Aktuelles.<br>
Nachteile hierbei sind die Anfälligkeit für Diebe bei Zinsen, und bei Aktien die schlechte Kalkulierbarkeit von Dividenden und Wachstum und die Tatsache, dass auch hier das Geld schnell "verfallen" kann wenn das andere Syndikat z.B. einen Krieg verliert. Bei Aktien muss man sich auch darüber im Klaren sein, dass man nicht immer sofort an sein Geld heran kommt. Letztendlich kann durch stark steigende Rohstoffpreise der Wert des eigenen Geldes auch schnell sinken.</p>
<br>
<p><i>Um wachsen zu können braucht ein Konzern Grund und Boden - dieser kann hinzu gekauft oder durch Angriff von anderen Konzernen geklaut werden.</i><br><br>
Landkauf hat den Vorteil, dass man nach eigener Kontrolle wächst. Als Nachteil kommt hier vor allem der stark steigende Kostenfaktor ins Spiel, der am Ende ziemlich groß werden kann.<br><br>
Angriff scheint damit auf den ersten Blick die billigere, vorteilhaftere Variante - man schickt einem kleineren Gegner ein paar Einheiten auf den Hals und holt sich einige Hektar und zahlt nichts dafür außer ein paar verlorenen Einheiten.<br>
Bei näherer Betrachtung ergeben sich jedoch folgende Probleme: Es gibt nicht immer passende Ziele, vor allem nicht in der "benötigten" Größe (optimalerweise größer als man selbst), man macht sich Feinde und man wird möglicherweise genau beäugt, ob man noch genug Verteidigung zu Hause hat. Und vor allem darf man eines nicht vernachlässigen: Wenn man genügend Militär vorhalten will, um effektive Angriffe führen zu können, muss man einen erheblichen Teil seine Landes für Lagerplatz opfern, der normalerweise Gewinnbringend (siehe oben) bebaut werden könnte. 
Tendenziell lohnt sich Angriff vor allem für Strategien, die sowieso viel Militär vorhalten (Einheitenverkauf), und während Kriegen in Organisation mit dem Syndikat, am meisten.</p>
<br>
<p><i>Ein weiterer, wichtiger Aspekt ist der optimale Erwerb von Militär und Spionen, um für sein sauer verdientes Geld die beste Leistung heraus zu holen.</i><br><br>
Einmal kann man es sich sehr einfach machen und am Global Market einkaufen - hierbei erhält man sein Militär sehr schnell, muss sich nicht aufwendig um Forschungen kümmern (speziell Advanced / Hightech Unit Construction) bzw. Land für Fabriken opfern oder alle Ressourcen in passender Menge vorhalten.<br>
Nachteile sind hierbei, dass man sein Militär selten zum (quasi) optimalen Preis erhält, der Markt möglicherweise zu einem Zeitpunkt, wo man seine Einheiten dringend benötigt, leer gekauft ist oder die Preise momentan sehr hoch sind.<br><br>
Beim Selbstbau bekommt man Einheiten zum optimalen Preis, was bei den hohen Kosten, die Militär und Spione beim Wachstum einnehmen, durchaus relevant ist - außerdem kann (sollte) man, wenn man schon Fabriken besitzt, auch gleich den aktuell "überschüssigen" Teil seiner Einheiten am Globalen Markt zum Verkauf anbieten.<br>
Nachteilig wirkt sich hier der Zwang aus, Land für Fabriken und Kraftwerke sowie Zeit für passende Forschungen zu opfern.</p>
<br>
<p><i>Letztlich steht man vor der Frage, ob man Bonusgebäude nutzen will. Fabriken sowie Geheimdienstzentren (SL) sind allgemein bekannt und anerkannt und müssen hier nicht näher behandelt werden.</i><br>
Wendet man sich jedoch anderen zu, stellen sich viele die Frage, wozu diese überhaupt nötig seien, denn sie würden ja keinen Networth bringen.<br><br>
Vorteile hier ist eindeutig die Kosteneffizienz, weil man seine Gebäude billiger baut, weniger für die gleiche Verteidigungs- / Angriffsmacht aufbringen muss oder sein Militär preiswert und sicher aufrüsten kann. Sich darauf zu konzentrieren, das letzte Quäntchen Networth aus seinem Konzern zu holen, kann man, wenn man groß ist und über entsprechende Einnahmen verfügt, während man vorher verhältnismäßig schnell, weil preiswert, wachsen kann. Außerdem gibt es verschiedene Einnahmen, die unabhängig vom eingesetzten Land sind, so dass man diese wesentlich besser ausnutzt als jemand, der sein Wachstum aus purem Umsatz zieht.<br><br>
Nachteil hierbei ist, dass man auf diesen speziellen Bonus eingeschränkt ist, für den man eventuell nur selten Verwendung und man somit Land die meiste Zeit ohne Gewinn verbraucht hat. Auch wird natürlich dadurch die Flexibilität eingeschränkt, die einem die pure Macht von vielen Ressourcen und Militär gibt.</p>
<br>
<p><i><i>Nähere (Beispiel-)Berechnungen unter Beachtung obiger Aspekte sollten einem helfen, die optimale Strategie zu finden bzw. vor allem auch eine gewählte "Haupt"strategie im Detail erfolgreich umzusetzen.</i></i></p>

<?